# -*- coding: utf-8 -*-
"""projeto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uer85qGot8j66cLJV9Jn9flsSIEEiuEE

Passo 1: Importar Base de dados
"""

import pandas as pd

tabela_clientes = pd.read_csv(r"/content/drive/MyDrive/ClientesBanco.csv", encoding="latin1")
tabela_clientes = tabela_clientes.drop("CLIENTNUM", axis=1)
display(tabela_clientes)

"""Passo 2: Tratamento da base de dados"""

tabela_clientes = tabela_clientes.dropna()#exclui as linhas que tem itens vazios
display(tabela_clientes.info())
display(tabela_clientes.describe())

"""Passo 3: Análisar os dados

- Queremos descobrir o motivo dos clientes cancelarem
"""

display(tabela_clientes['Categoria'].value_counts())
display(tabela_clientes['Categoria'].value_counts(normalize=True))

"""Seu objetivo: Analisar o 80/20

Olhar todas as caracteristicas dos clietnes e descobrir os PRINCIPAIS MOTIVOS de Cancelamento.
"""

import plotly.express as px
#LINK https://plotly.com/python/plotly-express/
#passo para criar graficos
#passo 1: Criar a figura
#passo 2: Exibir a figura
for coluna in tabela_clientes:
  #Criar o gráfico
  fig = px.histogram(tabela_clientes, x=coluna, color="Categoria")
  #Comando abaixo mostrará o grafico
  fig.show()

"""O que conseguimos perceber análisando os gráficos?

1.   Quase todos os clientes que cancelaram são da categoria BLUE
2.   Quanto mais o cliente entra em contato, aumenta as chances de cancelamento -> Plano de ação: Analisar o motivo do contato/Tratar os clientes que mais entraram em contato
3.   Quem menos ultiliza cancelar o cartão
      - Com mais de 80 transações o cliente não cancela mais o cartão
      - Clientes com menos de 60 transações são muito criticos
      - A mesma coisa acontece com a quantidade de transação
"""