# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9zB08u3yLcZGf7B2RJfxocyHv9aoyag

Passo a passo de construçao do código:

- Passo 1: Importar a base de dados
- Passo 2: Calcular o faturamento de cada loja
- Passo 3: Calcular a quantidade de produtos vendidos de cada loja.
- Passo 4: Calcular o ticket médio dos produtos de cada loja
- Passo 5: Enviar e-mail para a diretoria
- Passo 6: Enviar e-mail para para cada loja

Passo 1: Importar a base de dados
"""

import pandas as pd

tabela_vendas = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx")

"""Passo 2: Calcular o faturamento da loja"""

tabela_faturamento = tabela_vendas[['ID Loja', 'Valor Final']].groupby('ID Loja').sum() 
tabela_faturamento = tabela_faturamento.sort_values(by='Valor Final', ascending=False )
display(tabela_faturamento)

"""Passo 3: Calcular a quantidade de produtos vendidos em cada loja."""

tabela_quantidade = tabela_vendas[['ID Loja', 'Quantidade']].groupby('ID Loja').sum() 
tabela_quantidade = tabela_quantidade.sort_values(by='ID Loja', ascending=True )
display(tabela_quantidade)

"""- Passo 4: Calcular o ticket médio dos produtos de cada loja"""

ticket_medio = (tabela_faturamento['Valor Final'] / tabela_quantidade['Quantidade']).to_frame()
ticket_medio = ticket_medio.rename(columns={0: "Ticket Médio"})
display(ticket_medio)

"""Função enviar e-mail"""

def enviar_email(nome_da_loja, tabela):
  import smtplib
  import email.message

  server = smtplib.SMTP('smtp.gmail.com:587')  
  corpo_email = f"""
  <p>Prezados,</p>
  <p>Segue relatório de vendas</p>
  {tabela.to_html()}
  <p>Qualquer Duvida estou a disposição</p>
  """  
  msg = email.message.Message()
  msg['Subject'] = f"Relatório de vendas - {nome_da_loja}"
    
  # Fazer antes (apenas na 1ª vez): Ativar Aplicativos não Seguros.
  # Gerenciar Conta Google -> Segurança -> Aplicativos não Seguros -> Habilitar
  # Caso mesmo assim dê o erro: smtplib.SMTPAuthenticationError: (534,
  # Você faz o login no seu e-mail e depois entra em: https://accounts.google.com/DisplayUnlockCaptcha
  msg['From'] = 'gabrielsiqueiradev@gmail.com'
  msg['To'] = 'imleirbag5@gmail.com'
  password = "Alm#2018"
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(corpo_email )
    
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

"""Passo 5: Enviar e-mail"""

tabela_completa = tabela_faturamento.join(tabela_quantidade).join(ticket_medio)
display(tabela_completa)
enviar_email("Diretoria", tabela_completa)

"""passo 6: enviar email para cada loja"""

lista_lojas = tabela_vendas["ID Loja"].unique()
for loja in lista_lojas:
  tabela_loja = tabela_vendas.loc[tabela_vendas['ID Loja'] == loja ,['ID Loja', 'Quantidade', 'Valor Final']]
  tabela_loja = tabela_loja.groupby("ID Loja").sum()
  tabela_loja['Ticket Medio'] = tabela_loja["Valor Final"]/ tabela_loja["Quantidade"]
  enviar_email(loja, tabela_loja)